### ISSUE TITLE
cg-make-snapshot.sh only finds one subgroup (Crabgrass "committee") despite many subgroups existing

### ISSUE THREAD

**Issue by dauge** [meitar/crabgrass-tools#11]
I use crabgrass-tool for daily backup. Since upgrading my machine to stretch, only group and one subgroup is found. but the group count many subgroups.

`xxx@yyy:~$ /opt/crabgrass-tools/cg-make-snapshot.sh --quiet --dry-run --tor --user cguser --password ksducfhlwsdjewnkfh --subgroup --download-directory /home/xxx/ cggroup

Illegal option -s

Usage: /usr/bin/which [-a] args

Illegal option -s

Usage: /usr/bin/which [-a] args

Logging in as cguser...

Finding subgroups for cggroup...

Mirroring group cggroup with all subgroups: cggroup+firstsubgroup

torsocks /usr/bin/wget --quiet --load-cookies cg-make-snapshot.sh_cookies.9cHTH --mirror --include /cggroup,/groups/cggroup,/assets,/cggroup+firstsubgroup,/groups/cggroup+firstsubgroup --convert-links --retry-connrefused --reject edit.html --directory-prefix /home/xxx/ --page-requisites --html-extension https://we.riseup.net/cggroup/ https://we.riseup.net/cggroup+firstsubgroup
`

**Comment by dauge** [comment]
Do you need more information for this issue ?

**Comment by fabacab** [comment]
> Do you need more information for this issue ?

No, just time/motivation to look into it. It's not high on my priority list at the moment, sorry. :\

**Comment by dauge** [comment]
OK, thanks for your update

**Comment by grmpflprmpfl** [comment]
I've looked a bit into it. The problem seems to be in the line
`read -r -a subgroups <<< $(getSubgroups "$group")`

getSubgroups returns all the subgroups correctly (I tried without the "read" command), but somehow in this line, only the first one gets written into "subgroups". Sadly, my knowledge of shell is too limited to really understand, why this happens.

**Comment by fabacab** [comment]
@grmpflprmpfl Thanks for taking the time.

> `getSubgroups` returns all the subgroups correctly (I tried without the "read" command), but somehow in this line, only the first one gets written into "subgroups". Sadly, my knowledge of shell is too limited to really understand, why this happens.

The `$subgroups` shell variable is an array (the `-a` option to `read`), so what *should* be happening is that each group name is a new element of that array, split on `$IFS` (the Internal Field Separator). If you're not already familiar with arrays in Bash, look that up and then see if you can access successive elements of the array, which *should* contain the successive names of the groups.

**Comment by dauge** [comment]
thanks for the fix
