### ISSUE TITLE
Uppermost <group>+<subgroup> index.html file is not downloaded

### ISSUE THREAD

**Issue by jnachtigall** [meitar/crabgrass-tools#6]
If you do a `wget ... --html-extension  https://we.riseup.net/<group>+<subgroup>` then wget thinks that  `https://we.riseup.net/<group>+<subgroup>` is like `https://we.riseup.net/<group>+<subgroup>.html`. Wget then fails to download this index.html like overview page of each subgroup because of the given `--include` directories limits disallows it. 

I am not sure how to resolve this. Best way would be if crabgrass would link to subgroups always with a trailing `/` slash. But maybe there is also another possible way. All other files within `https://we.riseup.net/<group>+<subgroup>/all_other_files` get correctly downloaded, it is just the overview file.

Maybe the `include` list can be overriden just for these single files?!

**Comment by fabacab** [comment]
I know @Azul mentioned reviewing how Crabgrass links to things recently, so I just wanna CC them.

**Comment by azul** [comment]
I think `--adjust-extension` `--convert-links` as wget options might also fix this issue. At least i think it was what i used when i backed up the public pages of a whole install.
It will download the overview file and save it as group+committee.html and change all other links to point to it if i recall correctly.

**Comment by azul** [comment]
ah. sorry. Just saw the change in the proposed fix. My thinking was not about the regexp. And i see you already are using html-extension.

**Comment by jnachtigall** [comment]
@azul I think it's just recommended behaviour for CMS if 
- Internal links to subgroups' overview page would always be created as `https://we.riseup.net/<group>+<subgroup>/` (that is with trailing slash). If it is just `https://we.riseup.net/<group>+<subgroup>` (without trailing slash) then wget has no chance to see that this is kind of folder instead of page
- For external links to `https://we.riseup.net/<group>+<subgroup>` (no trailing slash) do a http redirect to `https://we.riseup.net/<group>+<subgroup>/` (trailing slash)

This way it's also handled by other CMS like WordPress. 

If you agree, then I can create an issue at crabgrass-core for this (though I am with you that there are more pressing issues ;)
